export const TOGGLE_PAD = 'TOGGLE_PAD'
export const ADVANCE_TICK = 'ADVANCE_TICK'
export const NOTE_LOADED = 'NOTE_LOADED'
export const TOGGLE_KLING ='TOGGLE_KLING'
export const CREATE_INSTRUMENT ='CREATE_INSTRUMENT'
export const ADD_PAD ='ADD_PAD'
export const ADD_COUNT ='ADD_COUNT'
export const CREATE_BEAT ='CREATE_BEAT'
